---
- name: Show OCP-V VM Infomation
  hosts: all

  tasks:
    - name: Get a list of all VirtualMachines
      redhat.openshift_virtualization.kubevirt_vm_info:
#        namespace: default
      register: vm_list

    - name: Display VM List
      ansible.builtin.debug:
        var: vm_list
      
